table Sales
	lineageTag: fadd0681-8450-4826-b80d-49136a3e27d2

	column saleskey
		dataType: int64
		formatString: 0
		lineageTag: f266e825-ea39-47d0-ab11-5b9b6eaeaa68
		summarizeBy: none
		sourceColumn: saleskey

		annotation SummarizationSetBy = User

	column date
		dataType: dateTime
		isHidden
		formatString: Long Date
		isAvailableInMdx: false
		lineageTag: d2f37868-5183-4627-a043-c974c311f7a1
		summarizeBy: none
		sourceColumn: date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column channelkey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: dcdd4df8-c742-4ea4-83c9-87393e3c9cc2
		summarizeBy: none
		sourceColumn: channelkey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column storekey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 732b3b21-b4b4-4f7d-b18f-3d23cec61b1b
		summarizeBy: none
		sourceColumn: storekey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column productkey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 67ebbaf5-bd9d-4ced-a674-de17043b0eed
		summarizeBy: none
		sourceColumn: productkey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column promotionkey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 9e2d0209-ca43-4228-ab74-c8fa06ed1625
		summarizeBy: none
		sourceColumn: promotionkey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Unit Cost'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		lineageTag: 8f7defec-dd63-402c-8164-b07c77036441
		summarizeBy: none
		sourceColumn: Unit Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		lineageTag: b1ea3f29-976a-46ae-be2d-8e2e6ada6554
		summarizeBy: none
		sourceColumn: Unit Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Quantity'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 3719e373-451d-4d11-b4ae-0eed227024e4
		summarizeBy: none
		sourceColumn: Sales Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Return Quantity'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 4afd515d-780b-4cca-93f4-9e407e201b41
		summarizeBy: none
		sourceColumn: Return Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Discount Quantity'
		dataType: int64
		formatString: 0
		lineageTag: 03740376-0fbf-4763-8131-d9ea01c9c948
		summarizeBy: none
		sourceColumn: Discount Quantity

		annotation SummarizationSetBy = User

	column geographykey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 645e6da9-e774-4781-aec3-6025aef14aaa
		summarizeBy: none
		sourceColumn: geographykey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "contoso_db"),
				    public_sales = Source{[Schema="public",Item="sales"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_sales,{{"geographykey", Int64.Type}, {"Unit Cost", Currency.Type}, {"Unit Price", Currency.Type}, {"date", type date}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"saleskey", "date", "channelkey", "storekey", "productkey", "promotionkey", "Unit Cost", "Unit Price", "Sales Quantity", "Return Quantity", "Discount Quantity", "geographykey"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

