createOrReplace

	table Promotion
		lineageTag: 3ec13964-fe23-401c-8c74-d15b430cb660

		column 'Promotion Key'
			dataType: string
			isHidden
			isKey
			lineageTag: d274bde8-56ee-45aa-8a03-2a5ee5a31600
			summarizeBy: none
			sourceColumn: Promotion Key
			isAvailableInMdx: false

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column 'Promotion Label'
			dataType: string
			lineageTag: 94008e2e-1f58-4cd0-a6d1-a1c6fe662386
			summarizeBy: none
			sourceColumn: Promotion Label

			annotation SummarizationSetBy = Automatic

		column 'Promotion Name'
			dataType: string
			lineageTag: 5edc1bb4-2cb8-4122-94eb-253286a8fad1
			summarizeBy: none
			sourceColumn: Promotion Name

			annotation SummarizationSetBy = Automatic

		column 'Discount Percent'
			dataType: string
			lineageTag: a3acf098-3824-45e3-b270-86619647e214
			summarizeBy: none
			sourceColumn: Discount Percent

			annotation SummarizationSetBy = Automatic

		column 'Start Date'
			dataType: string
			lineageTag: 544ca1e0-2da7-41b3-846c-69ab3dfa8651
			summarizeBy: none
			sourceColumn: Start Date

			annotation SummarizationSetBy = Automatic

		column 'End Date'
			dataType: string
			lineageTag: 914121c4-246f-4537-a957-388a8ec6328a
			summarizeBy: none
			sourceColumn: End Date

			annotation SummarizationSetBy = Automatic

		partition Promotion-ae564260-8dca-4fef-9284-8f67d8919cc0 = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents("C:\Users\tunde\OneDrive\Desktop\Contoso Data\Promotion.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"PromotionLabel", "Promotion Label"}, {"PromotionName", "Promotion Name"}, {"PromotionKey", "Promotion Key"}, {"DiscountPercent", "Discount Percent"}, {"StartDate", "Start Date"}, {"EndDate", "End Date"}})
					in
					    #"Renamed Columns"

		annotation PBI_NavigationStepName = Navigation

		annotation PBI_ResultType = Table

