table Promotion
	lineageTag: b2a3ac28-64fe-4c3c-a2d3-a7325b0df6ef

	column 'Promotion Key'
		dataType: int64
		formatString: 0
		lineageTag: 65d14dab-6630-42d6-96ed-77d8a9d975f4
		summarizeBy: none
		sourceColumn: Promotion Key

		annotation SummarizationSetBy = Automatic

	column 'Promotion Label'
		dataType: int64
		formatString: 0
		lineageTag: 7d716e5e-0456-498a-a365-194330cfe209
		summarizeBy: none
		sourceColumn: Promotion Label

		annotation SummarizationSetBy = Automatic

	column 'Promotion Name'
		dataType: string
		lineageTag: f20cd1ff-ceeb-4edb-b1ee-687bb23c6eee
		summarizeBy: none
		sourceColumn: Promotion Name

		annotation SummarizationSetBy = Automatic

	column 'Discount Percent'
		dataType: decimal
		lineageTag: 9a2128bf-9de1-44ff-be76-6099a8dc6228
		summarizeBy: none
		sourceColumn: Discount Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Start Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: e06128c4-d292-4b1f-8800-ff5716cb9b8d
		summarizeBy: none
		sourceColumn: Start Date

		annotation SummarizationSetBy = Automatic

	column 'End Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: a6569b07-7b76-4265-9bd1-d622a0a794ec
		summarizeBy: none
		sourceColumn: End Date

		annotation SummarizationSetBy = Automatic

	partition Promotion = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "contoso_db"),
				    public_promotion = Source{[Schema="public",Item="promotion"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_promotion,{{"Discount Percent", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

